kind: CronJob
apiVersion: batch/v1
metadata:
  name: automation-controller-metrics-utility-gather-node
  namespace: ansible-automation-platform
spec:
  schedule: '*/1 * * * *'
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: gather-node
          containers:
            - resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              name: automation-controller-metrics-utility-gather-node
              imagePullPolicy: Always
              image: 'quay.io/itdove/metrics-utility-poc:latest'
          restartPolicy: Never
